Django_Web_Programing/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from mysite import views

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("", views.index),
]

# templates에 페이지가 있다면설정하지 않아도 자동으로 찾아간다.
# handler404 = "mysite.views.error_404_view"
# handler500 = "mysite.views.error_500_view"

Django_Web_Programing/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # ex: /polls/survey/
    path("survey/", views.survey, name="survey"),
    # ex: /polls/survey/thanks/
    path("survey/thanks/", views.thanks, name="thanks"),
]

Django_Web_Programing/mysite/polls/models.py
from django.db import models
from django.core.validators import (
    MaxLengthValidator,
    MinLengthValidator,
    MinValueValidator,
    MaxValueValidator,
)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    owner = models.CharField(
        max_length=200,
        blank=True,
        validators=[MinLengthValidator(3), MaxLengthValidator(10)],
    )

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Survey(models.Model):
    user_name = models.CharField(max_length=200)
    user_age = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)]
    )

    def __str__(self):
        return f"{self.user_name}_{self.user_age}"

Django_Web_Programing/mysite/polls/forms.py
from django import forms

# class SurveyForm(forms.Form):
#     # https://docs.djangoproject.com/en/4.1/ref/forms/widgets/#built-in-widgets
#     user_name = forms.CharField(
#         label='Your name',
#         max_length=100,
#         widget=forms.TextInput(attrs={'class': 'form-control'}))
#     user_age = forms.IntegerField(
#         label='Your age',
#         widget=forms.NumberInput(attrs={'class': 'form-control'}))

from django.forms import ModelForm, TextInput, NumberInput
from polls.models import Survey


class SurveyForm(ModelForm):
    # https://docs.djangoproject.com/en/4.1/topics/forms/modelforms/
    class Meta:
        model = Survey
        # fields = ['user_name', 'user_age'] # select the fields
        fields = "__all__"  # select the al l the fields
        labels = {"user_name": "User Name", "user_age": "User Age"}
        widgets = {
            "user_name": TextInput(attrs={"class": "form-control"}),
            "user_age": NumberInput(attrs={"class": "form-control"}),
        }

Django_Web_Programing/mysite/mysite/views.py
from django.shortcuts import render


def index(request):
    # return HttpResponse("main index")
    return render(request, "main.html")


def error_404_view(request, exception):
    # return HttpResponseNotFound("The page is not found!")
    return render(request, "404.html")


def error_500_view(request):
    return render(request, "500.html")

Django_Web_Programing/mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .forms import SurveyForm
from django.template import loader
from .models import Choice, Survey, Question


# def index(request):
#     # return HttpResponse("Hello, world. You're at the polls index.")
#     # return HttpResponseRedirect(
#     #     reverse('detail', args=[1]))
#     # return HttpResponseRedirect(
#     #     reverse('detail', kwargs={'question_id': 1}))
#     ctx = {
#         "greetings": "Hello there!",
#         "location": {
#             "city": "Seoul",
#             "country": "South Korea"
#         },
#         "languages": ["Korean", "English"]
#     }
#     return render(request, 'polls/main.html', context=ctx)

# # using template
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list
#     }
#     return HttpResponse(template.render(context, request))


# using render
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {"question": question})


# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)

# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def survey(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = SurveyForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:

            # update
            # survey = Survey.objects.get(pk=1)
            # form = SurveyForm(request.POST, instance=survey)

            form.save()

            # print(form.cleaned_data['user_name'])
            # print(form.cleaned_data['user_age'])

            return HttpResponseRedirect(reverse("polls:thanks"))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SurveyForm()

    # return render(request, 'polls/survey.html', {'form': form})
    return render(request, "polls/survey_custom.html", {"form": form})


def thanks(request):
    return render(request, "polls/thanks.html", {})

Django_Web_Programing/mysite/polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
    {% comment %} https://docs.djangoproject.com/en/4.1/intro/tutorial04/ {% endcomment %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock content %}

Django_Web_Programing/mysite/polls/templates/polls/index.html
{% extends 'base.html' %}
{% block content %}
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                {% comment %} <li><a href="/polls/{{ quesiton.id}}">{{ question.question_text }}</a></li> {% endcomment %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock content %}

Django_Web_Programing/mysite/polls/templates/polls/main.html
{% extends 'base.html' %}
{% block content %}
    <h1>
        <a href="{% url 'polls:detail' question_id=10 %}">Question 10</a>
    </h1>
    <h1>{{ greetings|lower }}</h1>
    <h2>I am from {{ location.city }}, {{ location.country }}</h2>
    <h2>I speaks {{ location.0 }} and {{ location.1 }}</h2>
    <ul>
        {% for lang in languages %}
            <li>{{ lang }}</li>
        {% endfor %}

        {% for lang in languages %}
            <li>
                {% if lang == "Korean" %}
                    Wow!! You speak Korean!
                {% else %}
                    Alright, You speak English!
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <ul>
        {% for k, v in location.items %}
            <li>{{ k|capfirst }}: {{ v }}</li>
        {% endfor %}
    </ul>
{% endblock %}

Django_Web_Programing/mysite/polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}

Django_Web_Programing/mysite/polls/templates/polls/survey.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'polls:survey' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

Django_Web_Programing/mysite/polls/templates/polls/survey_custom.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'polls/polls_custom.css' %}" />
    <form action="{% url 'polls:survey' %}" method="post">
        {% csrf_token %}
        {% comment %} {{ form.as_div }} {% endcomment %}

        {% comment %} {{ form.user_name.label_tag }} {{ form.user_name }}
    {{ form.user_age.label_tag }} {{ form.user_age }} {% endcomment %}

        {% comment %} <div class="row mb-3">
        {{ form.user_name.errors }}
        <label class="col-sm-2 col-form-label" for="{{ form.user_name.id_for_label }}">Your name:</label>
        <div class="col-sm-10">
            {{ form.user_name }}
        </div>

        <label class="col-sm-2 col-form-label" for="{{ form.user_age.id_for_label }}">User age:</label>
        <div class="col-sm-10">
            {{ form.user_age }}
        </div>
    </div> {% endcomment %}

        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.label_tag }} {{ field }}
                {{ field.errors }}
                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}

        <div class="col-12">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
    </form>
{% endblock content %}

Django_Web_Programing/mysite/polls/templates/polls/thanks.html
{% extends 'base.html' %}
{% block content %}
    <h1>Thank you</h1>
{% endblock content %}

Django_Web_Programing/mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% block content %}
{% endblock %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</body>
</html>

Django_Web_Programing/mysite/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <img src="{% static 'mysite/django.png' %}" alt="Django image"/>
{% endblock %}